### ISSUE TITLE
docker file missing

### ISSUE THREAD

**Issue by poornas** [minio/xray#12]
Instructions to install xray broken - Dockerfile is missing from the GOPATH
Go->$ go get -d github.com/minio/xray
from the GOPATH
Go->$ go get -d github.com/minio/xray
Go->$ cd $GOPATH/src/github.com/minio/xray
Go->$  docker build . -t xray
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/krispy/work/src/github.com/minio/xray/Dockerfile: no such file or directory
Go->$ pwd
/Users/krispy/work/src/github.com/minio/xray
Go->$ ls
README.md                       main.go                         stream
haarcascade_frontalface_alt.xml opencv                          xray
Go->$

**Comment by harshavardhana** [comment]
https://github.com/minio/xray/blob/master/Dockerfile - here the file in the master you might have to pull the new changes..

```
go get -d -u github.com/minio/xray
```

**Comment by harshavardhana** [comment]
Dockerfile is available in the repo, closing this.
