### ISSUE TITLE
when alice stops, X-ray server stops abruptly.

### ISSUE THREAD

**Issue by deekoder** [minio/xray#13]
goroutine 792 [chan receive]:
github.com/minio/xray/cmd.writeFaceObject(0xc42001c140, 0xc42001a660)
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray-router.go:127 +0xa1
github.com/minio/xray/cmd.(*xrayHandlers).DetectObject(0xc4200cb030, 0x4542440, 0xc4200760d0, 0xc42019a0f0)
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray-router.go:158 +0x1ea
github.com/minio/xray/cmd.(*xrayHandlers).DetectObject-fm(0x4542440, 0xc4200760d0, 0xc42019a0f0)
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray-router.go:191 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42000dd20, 0x4542440, 0xc4200760d0, 0xc42019a0f0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420016910, 0x4542440, 0xc4200760d0, 0xc42019a0f0)
	/Users/Upheus1/go/src/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.serverHandler.ServeHTTP(0xc4200a6500, 0x4542440, 0xc4200760d0, 0xc4201001e0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420172100, 0x4542c80, 0xc42013ba40)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:2293 +0x44d

rax    0x0
rbx    0x6
rcx    0x7000079c5478
rdx    0x0
rdi    0x2503
rsi    0x6
rbp    0x7000079c54a0
rsp    0x7000079c5478
r8     0x7fffcff83650
r9     0x7fffcff45a50
r10    0x8000000
r11    0x206
r12    0x7000079c5600
r13    0x30
r14    0x7000079d6000
r15    0x8
rip    0x7fffcfff4dd6
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2

**Comment by harshavardhana** [comment]
@deekoder can you paste more information,  there must some more information above the backtrace as well like server logs etc. ?

**Comment by harshavardhana** [comment]
> @deekoder can you paste more information, there must some more information above the backtrace as well like server logs etc. ?

@deekoder do you have more information? on this.

**Comment by harshavardhana** [comment]
This is not happening anymore closing.
