### ISSUE TITLE
multiple faces are not detected accurately.

### ISSUE THREAD

**Issue by deekoder** [minio/xray#18]

**Comment by harshavardhana** [comment]
Multiple faces if are detected - we are not going to zoom anymore.

**Comment by harshavardhana** [comment]
This should be fixed already?

**Comment by harshavardhana** [comment]
> This should be fixed already?

The accuracy can be further improved keeping this as enhancement.

**Comment by harshavardhana** [comment]
Closing as duplicate and superseded by #24
