### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by deekoder** [minio/xray#19]
Deepas-MBP:xray Upheus1$ go run main.go 
INFO[0000] Started listening on ws://192.168.1.225:8080 
INFO[0000] Started listening on ws://127.0.0.1:8080     
ERRO[0059] Unable to read incoming binary message.       cause="websocket: close 1006 (abnormal closure): unexpected EOF" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[0541] Unable to read incoming binary message.       cause="websocket: close 1006 (abnormal closure): unexpected EOF" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[0672] Unable to read incoming binary message.       cause="websocket: close 1006 (abnormal closure): unexpected EOF" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[1657] Unable to read incoming binary message.       cause="websocket: close 1006 (abnormal closure): unexpected EOF" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[1735] Unable to read incoming binary message.       cause="websocket: close 1006 (abnormal closure): unexpected EOF" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[1756] Unable to read incoming binary message.       cause="websocket: close 1006 (abnormal closure): unexpected EOF" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[1771] Unable to read incoming binary message.       cause="read tcp 192.168.1.225:8080->192.168.1.145:44074: read: connection reset by peer" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[1817] Unable to read incoming binary message.       cause="websocket: close 1006 (abnormal closure): unexpected EOF" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[1883] Unable to read incoming binary message.       cause="read tcp 192.168.1.225:8080->192.168.1.145:48058: read: connection reset by peer" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[1960] Unable to read incoming binary message.       cause="read tcp 192.168.1.225:8080->192.168.1.145:40912: read: connection reset by peer" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
ERRO[2211] Unable to read incoming binary message.       cause="read tcp 192.168.1.225:8080->192.168.1.250:38494: read: connection reset by peer" source="[xray-router.go:150:github.com/minio/xray/cmd.(*xrayHandlers).DetectObject()]"
OpenCV Error: Bad argument (Bad image header) in cvCloneImage, file /tmp/opencv-20161221-94455-1gogyaj/opencv-2.4.13.2/modules/core/src/array.cpp, line 3108
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-20161221-94455-1gogyaj/opencv-2.4.13.2/modules/core/src/array.cpp:3108: error: (-5) Bad image header in function cvCloneImage

SIGABRT: abort
PC=0x7fffcfff4dd6 m=11
signal arrived during cgo execution

goroutine 5858 [syscall, locked to thread]:
runtime.cgocall(0x42f9fe0, 0xc4205fbdf0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/cgocall.go:131 +0x110 fp=0xc4205fbdc0 sp=0xc4205fbd80
github.com/lazywei/go-opencv/opencv._Cfunc_cvCloneImage(0x5a424c0, 0x0)
	??:0 +0x4a fp=0xc4205fbdf0 sp=0xc4205fbdc0
github.com/lazywei/go-opencv/opencv.(*IplImage).Clone(0x5a424c0, 0xc42001a600)
	/Users/Upheus1/go/src/github.com/lazywei/go-opencv/opencv/cxcore.go:84 +0x75 fp=0xc4205fbe38 sp=0xc4205fbdf0
github.com/minio/xray/cmd.(*xrayHandlers).detectObjects(0xc4200cb030, 0xc420332000, 0xf04c, 0xfe00)
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray-router.go:117 +0x330 fp=0xc4205fbfa0 sp=0xc4205fbe38
runtime.goexit()
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4205fbfa8 sp=0xc4205fbfa0
created by github.com/minio/xray/cmd.(*xrayHandlers).DetectObject
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray-router.go:160 +0x123

goroutine 1 [IO wait]:
net.runtime_pollWait(0x57b0098, 0x72, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4200cb8e0, 0x72, 0xc420475918, 0xc42000c0a8)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4200cb8e0, 0x4540b40, 0xc42000c0a8)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc4200cb880, 0x0, 0x453f080, 0xc4200fcd40)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc4200320d0, 0x29e8d60800, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc4200320d0, 0xc420475a40, 0xc420475a48, 0xc420475a38)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/tcpsock.go:209 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4200320d0, 0x43e3700, 0xc4200a6000, 0x4543d40, 0xc420011b60)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:2608 +0x2f
net/http.(*Server).Serve(0xc4200a6580, 0x4543780, 0xc4200320d0, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:2273 +0x1ce
net/http.(*Server).ListenAndServe(0xc4200a6580, 0x13, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:2219 +0xb4
github.com/minio/xray/cmd.registerApp.func1(0xc4200a49a0, 0xc4200a49a0, 0xc4200bbc47)
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray.go:131 +0x474
github.com/minio/cli.HandleAction(0x4343420, 0x43e3490, 0xc4200a49a0, 0xc42001a5a0, 0x0)
	/Users/Upheus1/go/src/github.com/minio/cli/app.go:491 +0xd4
github.com/minio/cli.(*App).Run(0xc4200a2b60, 0xc42000c260, 0x1, 0x1, 0x0, 0x0)
	/Users/Upheus1/go/src/github.com/minio/cli/app.go:265 +0x753
github.com/minio/cli.(*App).RunAndExitOnError(0xc4200a2b60)
	/Users/Upheus1/go/src/github.com/minio/cli/app.go:277 +0x53
github.com/minio/xray/cmd.Main()
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray.go:140 +0x2f
main.main()
	/Users/Upheus1/go/src/github.com/minio/xray/main.go:6 +0x14

goroutine 17 [syscall, 37 minutes, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5805 [IO wait]:
net.runtime_pollWait(0x57aff18, 0x72, 0x6)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42005e0d0, 0x72, 0xc4204717e8, 0xc42000c0a8)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42005e0d0, 0x4540b40, 0xc42000c0a8)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42005e070, 0xc4203b5a14, 0x1aa0, 0x43ec, 0x0, 0x4540b40, 0xc42000c0a8)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420032100, 0xc4203b5a14, 0x1aa0, 0x43ec, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/net.go:173 +0x70
bufio.(*Reader).Read(0xc420450060, 0xc4203b5a14, 0x1aa0, 0x43ec, 0x4994, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/bufio/bufio.go:199 +0xc7
github.com/gorilla/websocket.(*messageReader).Read(0xc4201381f8, 0xc4203b5a14, 0x43ec, 0x43ec, 0x5a8, 0x0, 0x0)
	/Users/Upheus1/go/src/github.com/gorilla/websocket/conn.go:913 +0x23a
bytes.(*Buffer).ReadFrom(0xc4204719f0, 0x57b01a8, 0xc4201381f8, 0xc42046d200, 0x0, 0x200)
	/usr/local/Cellar/go/1.7.4/libexec/src/bytes/buffer.go:176 +0x155
io/ioutil.readAll(0x57b01a8, 0xc4201381f8, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/io/ioutil/ioutil.go:33 +0x147
io/ioutil.ReadAll(0x57b01a8, 0xc4201381f8, 0x57b01a8, 0xc4201381f8, 0x0, 0x0, 0x1)
	/usr/local/Cellar/go/1.7.4/libexec/src/io/ioutil/ioutil.go:42 +0x3e
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc42001c140, 0xc42001a600, 0xc4200cb030, 0xc42038c000, 0xcfd6, 0xfe00, 0x0)
	/Users/Upheus1/go/src/github.com/gorilla/websocket/conn.go:958 +0x60
github.com/minio/xray/cmd.(*xrayHandlers).DetectObject(0xc4200cb030, 0x4543440, 0xc4200760d0, 0xc4204560f0)
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray-router.go:148 +0xbd
github.com/minio/xray/cmd.(*xrayHandlers).DetectObject-fm(0x4543440, 0xc4200760d0, 0xc4204560f0)
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray-router.go:195 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42000dd80, 0x4543440, 0xc4200760d0, 0xc4204560f0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420016910, 0x4543440, 0xc4200760d0, 0xc4204560f0)
	/Users/Upheus1/go/src/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.serverHandler.ServeHTTP(0xc4200a6580, 0x4543440, 0xc4200760d0, 0xc4201000f0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4200a6000, 0x4543c80, 0xc420156b00)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:2293 +0x44d

goroutine 5549 [IO wait]:
net.runtime_pollWait(0x57affd8, 0x72, 0x5)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42005e220, 0x72, 0xc420477788, 0xc42000c0a8)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42005e220, 0x4540b40, 0xc42000c0a8)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42005e1c0, 0xc4201e9000, 0x1000, 0x1000, 0x0, 0x4540b40, 0xc42000c0a8)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4200321b0, 0xc4201e9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc42001a780)
	/usr/local/Cellar/go/1.7.4/libexec/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc42001a780, 0xc4203bd18e, 0xc72, 0xc72, 0xd6a, 0x2, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/bufio/bufio.go:209 +0x1bc
github.com/gorilla/websocket.(*messageReader).Read(0xc4201500b8, 0xc4203bd18e, 0xc72, 0xc72, 0xf8, 0x0, 0x0)
	/Users/Upheus1/go/src/github.com/gorilla/websocket/conn.go:913 +0x23a
bytes.(*Buffer).ReadFrom(0xc4204779f0, 0x57b01a8, 0xc4201500b8, 0xc420236400, 0x0, 0x200)
	/usr/local/Cellar/go/1.7.4/libexec/src/bytes/buffer.go:176 +0x155
io/ioutil.readAll(0x57b01a8, 0xc4201500b8, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.7.4/libexec/src/io/ioutil/ioutil.go:33 +0x147
io/ioutil.ReadAll(0x57b01a8, 0xc4201500b8, 0x57b01a8, 0xc4201500b8, 0x0, 0x0, 0x1)
	/usr/local/Cellar/go/1.7.4/libexec/src/io/ioutil/ioutil.go:42 +0x3e
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc42001c280, 0xc42001a600, 0xc4200cb030, 0xc420332000, 0xf04c, 0xfe00, 0x0)
	/Users/Upheus1/go/src/github.com/gorilla/websocket/conn.go:958 +0x60
github.com/minio/xray/cmd.(*xrayHandlers).DetectObject(0xc4200cb030, 0x4543440, 0xc4200761a0, 0xc4201004b0)
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray-router.go:148 +0xbd
github.com/minio/xray/cmd.(*xrayHandlers).DetectObject-fm(0x4543440, 0xc4200761a0, 0xc4201004b0)
	/Users/Upheus1/go/src/github.com/minio/xray/cmd/xray-router.go:195 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42000dd80, 0x4543440, 0xc4200761a0, 0xc4201004b0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:1726 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420016910, 0x4543440, 0xc4200761a0, 0xc4201004b0)
	/Users/Upheus1/go/src/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.serverHandler.ServeHTTP(0xc4200a6580, 0x4543440, 0xc4200761a0, 0xc4201001e0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4200a6100, 0x4543c80, 0xc420014ac0)
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.7.4/libexec/src/net/http/server.go:2293 +0x44d

rax    0x0
rbx    0x6
rcx    0x7000013b9678
rdx    0x0
rdi    0x3003
rsi    0x6
rbp    0x7000013b96a0
rsp    0x7000013b9678
r8     0x7fffcff83650
r9     0x7fffcff45a50
r10    0x8000000
r11    0x206
r12    0x7000013b9800
r13    0x30
r14    0x7000013ca000
r15    0x8
rip    0x7fffcfff4dd6
rflags 0x206
cs     0x7
fs     0x0
gs     0x0

**Comment by harshavardhana** [comment]
Hopefully with all the new changes this won't happen, but we need to validate.

**Comment by harshavardhana** [comment]
should we close these bugs?

**Comment by harshavardhana** [comment]
This was related to frame motion detection but we don't have that anymore, we will have to try and reproduce these in time once we migrate to Simd package. Closing this bug for now.
