### ISSUE TITLE
server crashes on client connection

### ISSUE THREAD

**Issue by deekoder** [minio/xray#21]
go run main.go 
INFO[0000] Started listening on ws://192.168.1.225:8080 
INFO[0000] Started listening on ws://127.0.0.1:8080     
INFO[0321] Client metadata {"sensorName":"com.samsung.sensor.interrupt_gyro","sensorType":65579,"timestamp":1678955684726,"accuracy":3,"values":[[-1.0109406,0.037368774,-0.0041503906,0,0,0,0,0,0,0,0,0,0,0,0,0]]} 
fatal error: unexpected signal during runtime executionfatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime executionfatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x405acc5]

runtime stack:
fatal error: unexpected signal during runtime execution
stack trace unavailable
exit status 4

**Comment by harshavardhana** [comment]
should we close these bugs?

**Comment by harshavardhana** [comment]
Closing this as server migrated to newer code base.
