### ISSUE TITLE
server crashes after sometime with no operation on the client

### ISSUE THREAD

**Issue by deekoder** [minio/xray#22]
INFO[0287] Client metadata {"accuracy":10,"altitude":7,"bearing":0,"longitude":-122.16216943,"latitude":37.44671268,"speed":0} 
INFO[0287] Client metadata {"sensorName":"android.sensor.light","sensorType":5,"timestamp":2260406550497,"accuracy":3,"values":[[59,3879,0]]} 
INFO[0288] Client metadata {"accuracy":10,"altitude":7,"bearing":0,"longitude":-122.16216943,"latitude":37.4467127,"speed":0} 
INFO[0288] Client metadata {"sensorName":"android.sensor.pressure","sensorType":6,"timestamp":2261421626181,"accuracy":3,"values":[[1009.60956,0,0]]} 
INFO[0289] Client metadata {"accuracy":10,"altitude":7,"bearing":0,"longitude":-122.16216944,"latitude":37.44671273,"speed":0} 
INFO[0289] Client metadata {"sensorName":"com.qti.sensor.rgb","sensorType":33171013,"timestamp":2262438014120,"accuracy":3,"values":[[0.0012512207,6.2561035E-4,7.4768066E-4,0,0,0,0,0,0,0,0,0,0,0,0,0]]} 
fatal error: unexpected signal during runtime executionsignal: segmentation fault

**Comment by harshavardhana** [comment]
should we close these bugs?

**Comment by harshavardhana** [comment]
Closing this as server migrated to newer code base.
