### ISSUE TITLE
Server specify client calibrations

### ISSUE THREAD

**Issue by deekoder** [minio/xray#7]
- Zoom level
- Color 
- Resolution
- Flash
- Camera calibrations

**Comment by deekoder** [comment]
Camera on/off (edge cases may require this)
Display on/off

**Comment by harshavardhana** [comment]
> Zoom level

^^ This is supported already

> Display on/off

^^ This is supported already

Not sure if we need the rest at this point time.

**Comment by harshavardhana** [comment]
Closing this as not a priority item. We will bring this in later..
